# CMake generated Testfile for 
# Source directory: /home/force/Programmation/ESIR2/Soft/VISP/visp/modules/core
# Build directory: /home/force/Programmation/ESIR2/Soft/VISP/visp-build/modules/core
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testPerformanceLUT "testPerformanceLUT" "-c" "-d")
add_test(testIoPGM "testIoPGM" "-c" "-d")
add_test(testUndistortImage "testUndistortImage" "-c" "-d")
add_test(testIoPPM "testIoPPM" "-c" "-d")
add_test(testCreateSubImage "testCreateSubImage" "-c" "-d")
add_test(testConversion "testConversion" "-c" "-d")
add_test(testImagePoint "testImagePoint" "-c" "-d")
add_test(testReadImage "testReadImage" "-c" "-d")
add_test(testImageBinarise "testImageBinarise" "-c" "-d")
add_test(testXmlParser "testXmlParser" "-c" "-d")
add_test(testIoTools "testIoTools" "-c" "-d")
add_test(testPolygon "testPolygon" "-c" "-d")
add_test(testMutex "testMutex" "-c" "-d")
add_test(testThread "testThread" "-c" "-d")
add_test(testHistogram "testHistogram" "-c" "-d")
add_test(testTime "testTime" "-c" "-d")
add_test(testConvert "testConvert" "-c" "-d")
add_test(testPoseVector "testPoseVector" "-c" "-d")
add_test(testMatrixException "testMatrixException" "-c" "-d")
add_test(testRotation "testRotation" "-c" "-d")
add_test(testColVector "testColVector" "-c" "-d")
add_test(testRowVector "testRowVector" "-c" "-d")
add_test(testRobust "testRobust" "-c" "-d")
add_test(testKalmanVelocity "testKalmanVelocity" "-c" "-d")
add_test(testMatrixInverse "testMatrixInverse" "-c" "-d")
add_test(testTranslationVector "testTranslationVector" "-c" "-d")
add_test(testTwistMatrix "testTwistMatrix" "-c" "-d")
add_test(testMath "testMath" "-c" "-d")
add_test(testKalmanAcceleration "testKalmanAcceleration" "-c" "-d")
add_test(testSvd "testSvd" "-c" "-d")
add_test(testQuaternion "testQuaternion" "-c" "-d")
add_test(testMatrix "testMatrix" "-c" "-d")
add_test(testArray2D "testArray2D" "-c" "-d")
add_test(testCameraParametersConversion "testCameraParametersConversion" "-c" "-d")
