# CMake generated Testfile for 
# Source directory: /home/force/Programmation/ESIR2/Soft/VISP/visp/example/tracking
# Build directory: /home/force/Programmation/ESIR2/Soft/VISP/visp-build/example/tracking
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(mbtEdgeTracking "mbtEdgeTracking" "-c" "-d")
add_test(mbtEdgeKltTracking "mbtEdgeKltTracking" "-c" "-d")
add_test(mbtKltTracking "mbtKltTracking" "-c" "-d")
add_test(mbtEdgeTracking-cao "mbtEdgeTracking" "-c" "-f" "-d")
add_test(mbtEdgeKltTracking-cao "mbtEdgeKltTracking" "-c" "-f" "-d")
add_test(mbtKltTracking-cao "mbtKltTracking" "-c" "-f" "-d")
add_test(mbtEdgeTracking-cao-nocyl "mbtEdgeTracking" "-c" "-f" "-C" "-d")
add_test(mbtEdgeKltTracking-cao-nocyl "mbtEdgeKltTracking" "-c" "-f" "-C" "-d")
add_test(mbtEdgeTracking-cao-scanline "mbtEdgeTracking" "-c" "-f" "-l" "-d")
add_test(mbtEdgeKltTracking-cao-scanline "mbtEdgeKltTracking" "-c" "-f" "-l" "-d")
add_test(mbtKltTracking-cao-scanline "mbtKltTracking" "-c" "-f" "-l" "-d")
add_test(mbtEdgeMultiTracking-cao "mbtEdgeMultiTracking" "-c" "-f" "-d")
add_test(mbtEdgeKltMultiTracking-cao "mbtEdgeKltMultiTracking" "-c" "-f" "-d")
add_test(mbtKltMultiTracking-cao "mbtKltMultiTracking" "-c" "-f" "-d")
add_test(mbtEdgeMultiTracking-cao-scanline "mbtEdgeMultiTracking" "-c" "-f" "-l" "-d")
add_test(mbtEdgeKltMultiTracking-cao-scanline "mbtEdgeKltMultiTracking" "-c" "-f" "-l" "-d")
add_test(mbtKltMultiTracking-cao-scanline "mbtKltMultiTracking" "-c" "-f" "-l" "-d")
add_test(trackDot2WithAutoDetection "trackDot2WithAutoDetection" "-c" "-d")
add_test(trackMeCircle "trackMeCircle" "-c" "-d")
add_test(trackMeEllipse "trackMeEllipse" "-c" "-d")
add_test(trackMeLine "trackMeLine" "-c" "-d")
add_test(trackDot "trackDot" "-c" "-d")
add_test(trackDot2 "trackDot2" "-c" "-d")
add_test(templateTrackerPyramidal-SSDESM-Affine "templateTracker" "-c" "-l" "2" "-t" "0" "-w" "0" "-p" "-d")
add_test(templateTrackerPyramidal-SSDESM-Homography "templateTracker" "-c" "-l" "2" "-t" "0" "-w" "1" "-p" "-d")
add_test(templateTrackerPyramidal-SSDESM-HomographySL3 "templateTracker" "-c" "-l" "2" "-t" "0" "-w" "2" "-p" "-d")
add_test(templateTrackerPyramidal-SSDESM-SRT "templateTracker" "-c" "-l" "2" "-t" "0" "-w" "3" "-p" "-d")
add_test(templateTrackerPyramidal-SSDESM-Translation "templateTracker" "-c" "-l" "2" "-t" "0" "-w" "4" "-p" "-d")
add_test(templateTrackerPyramidal-SSDESM-RT "templateTracker" "-c" "-l" "2" "-t" "0" "-w" "5" "-p" "-d")
add_test(templateTrackerPyramidal-SSDForwardAdditional-Affine "templateTracker" "-c" "-l" "2" "-t" "1" "-w" "0" "-p" "-d")
add_test(templateTrackerPyramidal-SSDForwardAdditional-Homography "templateTracker" "-c" "-l" "2" "-t" "1" "-w" "1" "-p" "-d")
add_test(templateTrackerPyramidal-SSDForwardAdditional-HomographySL3 "templateTracker" "-c" "-l" "2" "-t" "1" "-w" "2" "-p" "-d")
add_test(templateTrackerPyramidal-SSDForwardAdditional-SRT "templateTracker" "-c" "-l" "2" "-t" "1" "-w" "3" "-p" "-d")
add_test(templateTrackerPyramidal-SSDForwardAdditional-Translation "templateTracker" "-c" "-l" "2" "-t" "1" "-w" "4" "-p" "-d")
add_test(templateTrackerPyramidal-SSDForwardAdditional-RT "templateTracker" "-c" "-l" "2" "-t" "1" "-w" "5" "-p" "-d")
add_test(templateTrackerPyramidal-SSDForwardCompositional-Affine "templateTracker" "-c" "-l" "2" "-t" "2" "-w" "0" "-p" "-d")
add_test(templateTrackerPyramidal-SSDForwardCompositional-Homography "templateTracker" "-c" "-l" "2" "-t" "2" "-w" "1" "-p" "-d")
add_test(templateTrackerPyramidal-SSDForwardCompositional-HomographySL3 "templateTracker" "-c" "-l" "2" "-t" "2" "-w" "2" "-p" "-d")
add_test(templateTrackerPyramidal-SSDForwardCompositional-SRT "templateTracker" "-c" "-l" "2" "-t" "2" "-w" "3" "-p" "-d")
add_test(templateTrackerPyramidal-SSDForwardCompositional-Translation "templateTracker" "-c" "-l" "2" "-t" "2" "-w" "4" "-p" "-d")
add_test(templateTrackerPyramidal-SSDForwardCompositional-RT "templateTracker" "-c" "-l" "2" "-t" "2" "-w" "5" "-p" "-d")
add_test(templateTrackerPyramidal-SSDInverseCompositional-Affine "templateTracker" "-c" "-l" "2" "-t" "3" "-w" "0" "-p" "-d")
add_test(templateTrackerPyramidal-SSDInverseCompositional-Homography "templateTracker" "-c" "-l" "2" "-t" "3" "-w" "1" "-p" "-d")
add_test(templateTrackerPyramidal-SSDInverseCompositional-HomographySL3 "templateTracker" "-c" "-l" "2" "-t" "3" "-w" "2" "-p" "-d")
add_test(templateTrackerPyramidal-SSDInverseCompositional-SRT "templateTracker" "-c" "-l" "2" "-t" "3" "-w" "3" "-p" "-d")
add_test(templateTrackerPyramidal-SSDInverseCompositional-Translation "templateTracker" "-c" "-l" "2" "-t" "3" "-w" "4" "-p" "-d")
add_test(templateTrackerPyramidal-SSDInverseCompositional-RT "templateTracker" "-c" "-l" "2" "-t" "3" "-w" "5" "-p" "-d")
add_test(templateTrackerPyramidal-ZNCCForwardAdditional-Affine "templateTracker" "-c" "-l" "2" "-t" "4" "-w" "0" "-p" "-d")
add_test(templateTrackerPyramidal-ZNCCForwardAdditional-Homography "templateTracker" "-c" "-l" "2" "-t" "4" "-w" "1" "-p" "-d")
add_test(templateTrackerPyramidal-ZNCCForwardAdditional-HomographySL3 "templateTracker" "-c" "-l" "2" "-t" "4" "-w" "2" "-p" "-d")
add_test(templateTrackerPyramidal-ZNCCForwardAdditional-SRT "templateTracker" "-c" "-l" "2" "-t" "4" "-w" "3" "-p" "-d")
add_test(templateTrackerPyramidal-ZNCCForwardAdditional-Translation "templateTracker" "-c" "-l" "2" "-t" "4" "-w" "4" "-p" "-d")
add_test(templateTrackerPyramidal-ZNCCForwardAdditional-RT "templateTracker" "-c" "-l" "2" "-t" "4" "-w" "5" "-p" "-d")
add_test(templateTrackerPyramidal-ZNCCInverseCompositional-Affine "templateTracker" "-c" "-l" "2" "-t" "5" "-w" "0" "-p" "-d")
add_test(templateTrackerPyramidal-ZNCCInverseCompositional-Homography "templateTracker" "-c" "-l" "2" "-t" "5" "-w" "1" "-p" "-d")
add_test(templateTrackerPyramidal-ZNCCInverseCompositional-HomographySL3 "templateTracker" "-c" "-l" "2" "-t" "5" "-w" "2" "-p" "-d")
add_test(templateTrackerPyramidal-ZNCCInverseCompositional-SRT "templateTracker" "-c" "-l" "2" "-t" "5" "-w" "3" "-p" "-d")
add_test(templateTrackerPyramidal-ZNCCInverseCompositional-Translation "templateTracker" "-c" "-l" "2" "-t" "5" "-w" "4" "-p" "-d")
add_test(templateTrackerPyramidal-ZNCCInverseCompositional-RT "templateTracker" "-c" "-l" "2" "-t" "5" "-w" "5" "-p" "-d")
add_test(templateTrackerPyramidal-MIInverseCompositional-Affine "templateTracker" "-c" "-l" "2" "-t" "9" "-w" "0" "-p" "-d")
add_test(templateTrackerPyramidal-MIInverseCompositional-Homography "templateTracker" "-c" "-l" "2" "-t" "9" "-w" "1" "-p" "-d")
add_test(templateTrackerPyramidal-MIInverseCompositional-HomographySL3 "templateTracker" "-c" "-l" "2" "-t" "9" "-w" "2" "-p" "-d")
add_test(templateTrackerPyramidal-MIInverseCompositional-SRT "templateTracker" "-c" "-l" "2" "-t" "9" "-w" "3" "-p" "-d")
add_test(templateTrackerPyramidal-MIInverseCompositional-Translation "templateTracker" "-c" "-l" "2" "-t" "9" "-w" "4" "-p" "-d")
add_test(templateTrackerPyramidal-MIInverseCompositional-RT "templateTracker" "-c" "-l" "2" "-t" "9" "-w" "5" "-p" "-d")
