# Generated by CMake 3.5.1

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget visp_core visp_detection visp_gui visp_io visp_klt visp_me visp_sensor visp_ar visp_blob visp_robot visp_visual_features visp_vs visp_vision visp_mbt visp_tt visp_tt_mi)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target visp_core
add_library(visp_core SHARED IMPORTED)

set_target_properties(visp_core PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/opencv;/usr/include"
  INTERFACE_LINK_LIBRARIES "/usr/lib/i386-linux-gnu/libopencv_videostab.so.2.4.9;/usr/lib/i386-linux-gnu/libopencv_video.so.2.4.9;/usr/lib/i386-linux-gnu/libopencv_ts.so.2.4.9;/usr/lib/i386-linux-gnu/libopencv_superres.so.2.4.9;/usr/lib/i386-linux-gnu/libopencv_stitching.so.2.4.9;/usr/lib/i386-linux-gnu/libopencv_photo.so.2.4.9;/usr/lib/i386-linux-gnu/libopencv_ocl.so.2.4.9;/usr/lib/i386-linux-gnu/libopencv_objdetect.so.2.4.9;/usr/lib/i386-linux-gnu/libopencv_ml.so.2.4.9;/usr/lib/i386-linux-gnu/libopencv_legacy.so.2.4.9;/usr/lib/i386-linux-gnu/libopencv_imgproc.so.2.4.9;/usr/lib/i386-linux-gnu/libopencv_highgui.so.2.4.9;/usr/lib/i386-linux-gnu/libopencv_gpu.so.2.4.9;/usr/lib/i386-linux-gnu/libopencv_flann.so.2.4.9;/usr/lib/i386-linux-gnu/libopencv_features2d.so.2.4.9;/usr/lib/i386-linux-gnu/libopencv_core.so.2.4.9;/usr/lib/i386-linux-gnu/libopencv_contrib.so.2.4.9;/usr/lib/i386-linux-gnu/libopencv_calib3d.so.2.4.9;/usr/lib/i386-linux-gnu/libpthread.so;/usr/lib/i386-linux-gnu/libz.so;/usr/lib/i386-linux-gnu/libm.so;/usr/lib/i386-linux-gnu/libnsl.so"
)

# Create imported target visp_detection
add_library(visp_detection SHARED IMPORTED)

set_target_properties(visp_detection PROPERTIES
  INTERFACE_LINK_LIBRARIES "visp_core;/usr/lib/i386-linux-gnu/libm.so;/usr/lib/i386-linux-gnu/libnsl.so"
)

# Create imported target visp_gui
add_library(visp_gui SHARED IMPORTED)

set_target_properties(visp_gui PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include"
  INTERFACE_LINK_LIBRARIES "visp_core;/usr/lib/i386-linux-gnu/libSM.so;/usr/lib/i386-linux-gnu/libICE.so;/usr/lib/i386-linux-gnu/libX11.so;/usr/lib/i386-linux-gnu/libXext.so;/usr/lib/i386-linux-gnu/libm.so;/usr/lib/i386-linux-gnu/libnsl.so"
)

# Create imported target visp_io
add_library(visp_io SHARED IMPORTED)

set_target_properties(visp_io PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include"
  INTERFACE_LINK_LIBRARIES "visp_core;/usr/lib/i386-linux-gnu/libjpeg.so;/usr/lib/i386-linux-gnu/libpng.so;/usr/lib/i386-linux-gnu/libz.so;/usr/lib/i386-linux-gnu/libm.so;/usr/lib/i386-linux-gnu/libnsl.so"
)

# Create imported target visp_klt
add_library(visp_klt SHARED IMPORTED)

set_target_properties(visp_klt PROPERTIES
  INTERFACE_LINK_LIBRARIES "visp_core;/usr/lib/i386-linux-gnu/libm.so;/usr/lib/i386-linux-gnu/libnsl.so"
)

# Create imported target visp_me
add_library(visp_me SHARED IMPORTED)

set_target_properties(visp_me PROPERTIES
  INTERFACE_LINK_LIBRARIES "visp_core;/usr/lib/i386-linux-gnu/libm.so;/usr/lib/i386-linux-gnu/libnsl.so"
)

# Create imported target visp_sensor
add_library(visp_sensor SHARED IMPORTED)

set_target_properties(visp_sensor PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include"
  INTERFACE_LINK_LIBRARIES "visp_core;/usr/lib/i386-linux-gnu/libdc1394.so;/usr/lib/i386-linux-gnu/libm.so;/usr/lib/i386-linux-gnu/libnsl.so"
)

# Create imported target visp_ar
add_library(visp_ar SHARED IMPORTED)

set_target_properties(visp_ar PROPERTIES
  INTERFACE_LINK_LIBRARIES "visp_core;visp_io;/usr/lib/i386-linux-gnu/libm.so;/usr/lib/i386-linux-gnu/libnsl.so"
)

# Create imported target visp_blob
add_library(visp_blob SHARED IMPORTED)

set_target_properties(visp_blob PROPERTIES
  INTERFACE_LINK_LIBRARIES "visp_core;/usr/lib/i386-linux-gnu/libm.so;/usr/lib/i386-linux-gnu/libnsl.so"
)

# Create imported target visp_robot
add_library(visp_robot SHARED IMPORTED)

set_target_properties(visp_robot PROPERTIES
  INTERFACE_LINK_LIBRARIES "visp_core;visp_gui;visp_io;visp_sensor;/usr/lib/i386-linux-gnu/libm.so;/usr/lib/i386-linux-gnu/libnsl.so"
)

# Create imported target visp_visual_features
add_library(visp_visual_features SHARED IMPORTED)

set_target_properties(visp_visual_features PROPERTIES
  INTERFACE_LINK_LIBRARIES "visp_core;visp_me;visp_blob;/usr/lib/i386-linux-gnu/libm.so;/usr/lib/i386-linux-gnu/libnsl.so"
)

# Create imported target visp_vs
add_library(visp_vs SHARED IMPORTED)

set_target_properties(visp_vs PROPERTIES
  INTERFACE_LINK_LIBRARIES "visp_core;visp_gui;visp_io;visp_me;visp_sensor;visp_blob;visp_robot;visp_visual_features;/usr/lib/i386-linux-gnu/libm.so;/usr/lib/i386-linux-gnu/libnsl.so"
)

# Create imported target visp_vision
add_library(visp_vision SHARED IMPORTED)

set_target_properties(visp_vision PROPERTIES
  INTERFACE_LINK_LIBRARIES "visp_core;visp_io;visp_me;visp_blob;visp_visual_features;/usr/lib/i386-linux-gnu/libm.so;/usr/lib/i386-linux-gnu/libnsl.so"
)

# Create imported target visp_mbt
add_library(visp_mbt SHARED IMPORTED)

set_target_properties(visp_mbt PROPERTIES
  INTERFACE_LINK_LIBRARIES "visp_core;visp_gui;visp_io;visp_klt;visp_me;visp_ar;visp_blob;visp_visual_features;visp_vision;/usr/lib/i386-linux-gnu/libm.so;/usr/lib/i386-linux-gnu/libnsl.so"
)

# Create imported target visp_tt
add_library(visp_tt SHARED IMPORTED)

set_target_properties(visp_tt PROPERTIES
  INTERFACE_LINK_LIBRARIES "visp_core;visp_io;visp_me;visp_blob;visp_visual_features;visp_vision;/usr/lib/i386-linux-gnu/libm.so;/usr/lib/i386-linux-gnu/libnsl.so"
)

# Create imported target visp_tt_mi
add_library(visp_tt_mi SHARED IMPORTED)

set_target_properties(visp_tt_mi PROPERTIES
  INTERFACE_LINK_LIBRARIES "visp_core;visp_io;visp_me;visp_blob;visp_visual_features;visp_vision;visp_tt;/usr/lib/i386-linux-gnu/libm.so;/usr/lib/i386-linux-gnu/libnsl.so"
)

# Import target "visp_core" for configuration "Release"
set_property(TARGET visp_core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(visp_core PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/force/Programmation/ESIR2/Soft/VISP/visp-build/lib/libvisp_core.so.3.0.1"
  IMPORTED_SONAME_RELEASE "libvisp_core.so.3.0"
  )

# Import target "visp_detection" for configuration "Release"
set_property(TARGET visp_detection APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(visp_detection PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/force/Programmation/ESIR2/Soft/VISP/visp-build/lib/libvisp_detection.so.3.0.1"
  IMPORTED_SONAME_RELEASE "libvisp_detection.so.3.0"
  )

# Import target "visp_gui" for configuration "Release"
set_property(TARGET visp_gui APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(visp_gui PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/force/Programmation/ESIR2/Soft/VISP/visp-build/lib/libvisp_gui.so.3.0.1"
  IMPORTED_SONAME_RELEASE "libvisp_gui.so.3.0"
  )

# Import target "visp_io" for configuration "Release"
set_property(TARGET visp_io APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(visp_io PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/force/Programmation/ESIR2/Soft/VISP/visp-build/lib/libvisp_io.so.3.0.1"
  IMPORTED_SONAME_RELEASE "libvisp_io.so.3.0"
  )

# Import target "visp_klt" for configuration "Release"
set_property(TARGET visp_klt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(visp_klt PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/force/Programmation/ESIR2/Soft/VISP/visp-build/lib/libvisp_klt.so.3.0.1"
  IMPORTED_SONAME_RELEASE "libvisp_klt.so.3.0"
  )

# Import target "visp_me" for configuration "Release"
set_property(TARGET visp_me APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(visp_me PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/force/Programmation/ESIR2/Soft/VISP/visp-build/lib/libvisp_me.so.3.0.1"
  IMPORTED_SONAME_RELEASE "libvisp_me.so.3.0"
  )

# Import target "visp_sensor" for configuration "Release"
set_property(TARGET visp_sensor APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(visp_sensor PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/force/Programmation/ESIR2/Soft/VISP/visp-build/lib/libvisp_sensor.so.3.0.1"
  IMPORTED_SONAME_RELEASE "libvisp_sensor.so.3.0"
  )

# Import target "visp_ar" for configuration "Release"
set_property(TARGET visp_ar APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(visp_ar PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/force/Programmation/ESIR2/Soft/VISP/visp-build/lib/libvisp_ar.so.3.0.1"
  IMPORTED_SONAME_RELEASE "libvisp_ar.so.3.0"
  )

# Import target "visp_blob" for configuration "Release"
set_property(TARGET visp_blob APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(visp_blob PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/force/Programmation/ESIR2/Soft/VISP/visp-build/lib/libvisp_blob.so.3.0.1"
  IMPORTED_SONAME_RELEASE "libvisp_blob.so.3.0"
  )

# Import target "visp_robot" for configuration "Release"
set_property(TARGET visp_robot APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(visp_robot PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/force/Programmation/ESIR2/Soft/VISP/visp-build/lib/libvisp_robot.so.3.0.1"
  IMPORTED_SONAME_RELEASE "libvisp_robot.so.3.0"
  )

# Import target "visp_visual_features" for configuration "Release"
set_property(TARGET visp_visual_features APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(visp_visual_features PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/force/Programmation/ESIR2/Soft/VISP/visp-build/lib/libvisp_visual_features.so.3.0.1"
  IMPORTED_SONAME_RELEASE "libvisp_visual_features.so.3.0"
  )

# Import target "visp_vs" for configuration "Release"
set_property(TARGET visp_vs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(visp_vs PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/force/Programmation/ESIR2/Soft/VISP/visp-build/lib/libvisp_vs.so.3.0.1"
  IMPORTED_SONAME_RELEASE "libvisp_vs.so.3.0"
  )

# Import target "visp_vision" for configuration "Release"
set_property(TARGET visp_vision APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(visp_vision PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/force/Programmation/ESIR2/Soft/VISP/visp-build/lib/libvisp_vision.so.3.0.1"
  IMPORTED_SONAME_RELEASE "libvisp_vision.so.3.0"
  )

# Import target "visp_mbt" for configuration "Release"
set_property(TARGET visp_mbt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(visp_mbt PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/force/Programmation/ESIR2/Soft/VISP/visp-build/lib/libvisp_mbt.so.3.0.1"
  IMPORTED_SONAME_RELEASE "libvisp_mbt.so.3.0"
  )

# Import target "visp_tt" for configuration "Release"
set_property(TARGET visp_tt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(visp_tt PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/force/Programmation/ESIR2/Soft/VISP/visp-build/lib/libvisp_tt.so.3.0.1"
  IMPORTED_SONAME_RELEASE "libvisp_tt.so.3.0"
  )

# Import target "visp_tt_mi" for configuration "Release"
set_property(TARGET visp_tt_mi APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(visp_tt_mi PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/force/Programmation/ESIR2/Soft/VISP/visp-build/lib/libvisp_tt_mi.so.3.0.1"
  IMPORTED_SONAME_RELEASE "libvisp_tt_mi.so.3.0"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
